version: '3.9'
services:
  dev:
    # image: cr0nus/aws-box:dev
    container_name: flask-dev
    build:
      context: .
    volumes:
      - .:/app
    stdin_open: true # docker run -i
    tty: true # docker run -t
    ports:
      - 80:80
